apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: tkgm1-cluster1
        url: https://kubernetes.default.svc
        env: dev
      - cluster: tkgm1-cluster1
        url: https://kubernetes.default.svc
        env: prod
  template:
    metadata:
      name: 'guestbook-{{env}}'
    spec:
      project: guestbook-project
      source:
        repoURL: https://github.com/mtritabaugh/guestbook.git
        targetRevision: HEAD
        path: '{{env}}'
      destination:
        server: '{{url}}'
        namespace: 'guestbook-{{cluster}}'
